name: Main
on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.19
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init test
      - name: Terraform Validate
        run: terraform validate test
      - name: Terraform Plan
        run: terraform plan test
